AWSTemplateFormatVersion: '2010-09-09'

Description:
    Template for deploying all Infrastructure-Level configuration stacks.


Resources:

 VPCSubnetsStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL:
      Fn::Sub: https://nestedcfn-basestack-s3bucket-1jfo1yre7glfu.s3-ap-southeast-2.amazonaws.com/cicd-test/Infrastructure-VPC-Subnets.yaml
      TimeoutInMinutes: '60'
      Tags:
        - Key: Name
          Value: Sample-nested-cfn-to-test
