AWSTemplateFormatVersion: '2010-09-09'

Description:
    Template for deploying all Infrastructure-Level configuration stacks.


Resources:

 VPCSubnetsStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: s3://nestedcfn-basestack-s3bucket-1jfo1yre7glfu/cicd-test/Infrastructure-VPC-Subnets.yaml
      TimeoutInMinutes: '60'
      Tags:
        - Key: Name
          Value: Sample-nested-cfn-to-test
