AWSTemplateFormatVersion: '2010-09-09'

Description:
    Template for deploying all Infrastructure-Level configuration stacks.

Parameters:

############ START PARAMETERS #######################################################################################################################

#General parameters

  CustomerName:
    Type: String
    MinLength: '3'
    MaxLength: '5'
    Description: >-
      Customer Name for stack naming purposes [Min 3-char, Max 5-char].

  DXCMgmntAccountID:
    Type: String
    MaxLength: '12'
    Default: 369513996270
    Description: >-
      DXC Management 12-digit AWS account ID.


#Child stack template URLs

  VPCSubnetsTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for VPC / IGW / PCX / Subnets / S3-Endpoints.

  VPCFlowLogsTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for VPC Flow Logs.

  VPCRouteTablesTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for Route Tables.

  VPCNACLSTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for Network ACLs.

  VPCSecurityGroupsTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for Security Groups.

  EC2InstanceProfileTemplateURL:
    Type: String
    Description: >-
      S3 URL of template for EC2 Instance Profiles.


#Availability zone parameters

  ThreeAvailabilityZonesActivatedParam:
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
    Description: >-
      Choose 'yes' to use all three Availability Zones of ap-southeast-2 (Sydney), or 'no' to use 2 (ap-southeast-2a and 2b).

  AZ1:
    Type: String
    Default: ap-southeast-2a
    Description: >-
      Name of first availability zone.

  AZ2:
    Type: String
    Default: ap-southeast-2b
    Description: >-
      Name of second availability zone.

  AZ3:
    Type: String
    Default: ap-southeast-2c
    Description: >-
      Name of third availability zone.

#VPC peering parameters

  VPCPeerID:
    Description: DXC Management Peer VPC ID.
    Type: String
    Default: vpc-940805f1

  VPCPeeringRoleARN:
    Type: String
    Description: >-
      ARN for VPC peering connection acceptance role - MUST be created manually beforehand.

#IPv4 top-layer CIDR parameters

  DXCMgmntCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 20.156.32.0/24
    Description: >-
      CIDR block of DXC Management VPC.

  CustomerCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR block of the customer VPC.


#IPv4 second-level CIDR parameters

  DMZCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR block for DMZ subnet.

  APPCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR block for Application subnet.

  DBCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR block for Database subnet.

  DSKTOPCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR block for Desktop subnet.


#Management security groups parameters

  MonitoringServersSGId:
    Type: String
    Description: >-
      Security group ID of DXC Monitoring Servers.
    Default: sg-71e2e615

  EndPointProtectionServersSGId:
    Type: String
    Description: >-
      Security group ID of DXC Endpoint Protection Servers.
    Default: sg-60231604

  BackupRecoveryServersSGId:
    Type: String
    Description: >-
      Security group ID of DXC Backup & Recovery Servers.
    Default: sg-d4dac0b0

  DXCMgmntServersSGId:
    Type: String
    Description: >-
      Security group ID of DXC Management Servers.
    Default: sg-4696b422

#S3 endpoints parameters

  S3EndpointCIDR1:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 52.0.0.0/8
    Description: >-
      S3 endpoint CIDR block ONE.

  S3EndpointCIDR2:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 54.0.0.0/8
    Description: >-
      S3 endpoint CIDR block TWO.


#IPv4 third-level CIDR parameters

  DMZ1A:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DMZ-1A Subnet.

  DMZ1B:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DMZ-1B Subnet.

  DMZ1C:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      (If 'yes' for 3 AZs): CIDR Block of DMZ-1C Subnet. Otherwise, leave as '--.--.--.--/--'

  APP1A:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of APP-1A Subnet.

  APP1B:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of APP-1B Subnet.

  APP1C:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      (If 'yes' for 3 AZs): CIDR Block of APP-1C Subnet. Otherwise, leave as '--.--.--.--/--'

  DB1A:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DB-1A Subnet.

  DB1B:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DB-1B Subnet.

  DB1C:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      (If 'yes' for 3 AZs): CIDR Block of DB-1C Subnet. Otherwise, leave as '--.--.--.--/--'

  DSKTOP1A:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DSKTOP-1A Subnet.

  DSKTOP1B:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      CIDR Block of DSKTOP-1B Subnet.

  DSKTOP1C:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Description: >-
      (If 'yes' for 3 AZs): CIDR Block of DSKTOP-1C Subnet. Otherwise, leave as '--.--.--.--/--'

############ END PARAMETERS #######################################################################################################################

############ START METADATA #######################################################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "General Details"
        Parameters:
          - CustomerName
          - DXCMgmntAccountID
      -
        Label:
          default: "Template URLs"
        Parameters:
          - VPCSubnetsTemplateURL
          - VPCFlowLogsTemplateURL
          - VPCRouteTablesTemplateURL
          - VPCNACLSTemplateURL
          - VPCSecurityGroupsTemplateURL
          - EC2InstanceProfileTemplateURL
      -
        Label:
          default: "Availability Zones"
        Parameters:
          - ThreeAvailabilityZonesActivatedParam
          - AZ1
          - AZ2
          - AZ3
      -
        Label:
          default: "DXC Management Security Groups"
        Parameters:
          - MonitoringServersSGId
          - EndPointProtectionServersSGId
          - BackupRecoveryServersSGId
          - DXCMgmntServersSGId
      -
        Label:
          default: "Top-Layer IPv4 CIDR Blocks"
        Parameters:
          - DXCMgmntCIDR
          - CustomerCIDR
      -
        Label:
          default: "Second-Layer (/20) IPv4 CIDR Blocks"
        Parameters:
          - DMZCIDR
          - APPCIDR
          - DBCIDR
          - DSKTOPCIDR
      -
        Label:
          default: "Third-Layer (/24) IPv4 CIDR Blocks"
        Parameters:
          - DMZ1A
          - DMZ1B
          - DMZ1C
          - APP1A
          - APP1B
          - APP1C
          - DB1A
          - DB1B
          - DB1C
          - DSKTOP1A
          - DSKTOP1B
          - DSKTOP1C
      -
        Label:
          default: "S3 Endpoints"
        Parameters:
          - S3EndpointCIDR1
          - S3EndpointCIDR2
    ParameterLabels:
      CustomerName:
        default: '* Customer Name'
      DXCMgmntAccountID:
        default: '* DXC Mgmt. Account ID'
      VPCSubnetsTemplateURL:
        default: '* VPC / IGW / PCX / Subnets / S3 Endpoints'
      VPCFlowLogsTemplateURL:
        default: '* VPC Flow Logs'
      VPCRouteTablesTemplateURL:
        default: '* Route Tables'
      VPCNACLSTemplateURL:
        default: '* Network ACLs'
      VPCSecurityGroupsTemplateURL:
        default: '* Security Groups'
      EC2InstanceProfileTemplateURL:
        default: '* Instance Profiles'
      ThreeAvailabilityZonesActivatedParam:
        default: '* Use All Three AZs'
      AZ1:
        default: '* AZ 1'
      AZ2:
        default: '* AZ 2'
      AZ3:
        default: '* AZ 3'
      MonitoringServersSGId:
        default: '* Monitoring Servers'
      EndPointProtectionServersSGId:
        default: '* Endpoint Protection Servers'
      BackupRecoveryServersSGId:
        default: '* Backup & Recovery Servers'
      DXCMgmntServersSGId:
        default: '* Management Servers'
      DXCMgmntCIDR:
        default: '* DXC Management CIDR'
      CustomerCIDR:
        default: '* Customer CIDR'
      DMZCIDR:
        default: '* DMZ'
      APPCIDR:
        default: '* Application'
      DBCIDR:
        default: '* Database'
      DSKTOPCIDR:
        default: '* Desktop'
      DMZ1A:
        default: '* DMZ 1A'
      DMZ1B:
        default: '* DMZ 1B'
      DMZ1C:
        default: '* DMZ 1C'
      APP1A:
        default: '* Application 1A'
      APP1B:
        default: '* Application 1B'
      APP1C:
        default: '* Application 1C'
      DB1A:
        default: '* Database 1A'
      DB1B:
        default: '* Database 1B'
      DB1C:
        default: '* Database 1C'
      DSKTOP1A:
        default: '* Desktop 1A'
      DSKTOP1B:
        default: '* Desktop 1B'
      DSKTOP1C:
        default: '* Desktop 1C'
      S3EndpointCIDR1:
        default: '* CIDR Block 1'
      S3EndpointCIDR2:
        default: '* CIDR Block 2'

############ END METADATA #######################################################################################################################


############ START CONDITIONS ###################################################################################################################

############ END CONDITIONS #####################################################################################################################


Resources:

 VPCSubnetsStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Ref VPCSubnetsTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        CustomerName: !Ref CustomerName
        CustomerCIDR: !Ref CustomerCIDR
        DXCMgmntAccountID: !Ref DXCMgmntAccountID
        ThreeAvailabilityZonesActivatedParam: !Ref ThreeAvailabilityZonesActivatedParam
        AZ1: !Ref AZ1
        AZ2: !Ref AZ2
        AZ3: !Ref AZ3
        DMZ1A: !Ref DMZ1A
        DMZ1B: !Ref DMZ1B
        DMZ1C: !Ref DMZ1C
        APP1A: !Ref APP1A
        APP1B: !Ref APP1B
        APP1C: !Ref APP1C
        DB1A: !Ref DB1A
        DB1B: !Ref DB1B
        DB1C: !Ref DB1C
        DSKTOP1A: !Ref DSKTOP1A
        DSKTOP1B: !Ref DSKTOP1B
        DSKTOP1C: !Ref DSKTOP1C
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref CustomerName, "INFR", "VPCSubnetsStack" ]]


 VPCFlowLogsStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    DependsOn : VPCSubnetsStack
    Properties:
      TemplateURL: !Ref VPCFlowLogsTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        CustomerVPCId: !GetAtt
          - VPCSubnetsStack
          - Outputs.CustomerVPCId
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref CustomerName, "INFR", "VPCFlowLogsStack" ]]


 VPCRouteTablesStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    DependsOn : VPCSubnetsStack
    Properties:
      TemplateURL: !Ref VPCRouteTablesTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        CustomerName: !Ref CustomerName
        DXCMgmntCIDR: !Ref DXCMgmntCIDR
        ThreeAvailabilityZonesActivatedParam: !Ref ThreeAvailabilityZonesActivatedParam
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref CustomerName, "INFR", "VPCRouteTablesStack" ]]



 VPCNACLSStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    DependsOn : VPCSubnetsStack
    Properties:
      TemplateURL: !Ref VPCNACLSTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        DMZCIDR: !Ref DMZCIDR
        APPCIDR: !Ref APPCIDR
        DBCIDR: !Ref DBCIDR
        DSKTOPCIDR: !Ref DSKTOPCIDR
        DXCMgmntCIDR: !Ref DXCMgmntCIDR
        S3EndpointCIDR1: !Ref S3EndpointCIDR1
        S3EndpointCIDR2: !Ref S3EndpointCIDR2
        ThreeAvailabilityZonesActivatedParam: !Ref ThreeAvailabilityZonesActivatedParam
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref CustomerName, "INFR", "VPCNACLSStack" ]]


 VPCSecurityGroupsStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    DependsOn : VPCSubnetsStack
    Properties:
      TemplateURL: !Ref VPCSecurityGroupsTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
          MonitoringServersSGId: !Ref MonitoringServersSGId
          EndPointProtectionServersSGId: !Ref EndPointProtectionServersSGId
          BackupRecoveryServersSGId: !Ref BackupRecoveryServersSGId
          DXCMgmntServersSGId: !Ref DXCMgmntServersSGId
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref CustomerName, "INFR", "VPCSecurityGroupsStack" ]]

Outputs:
  VPCSubnetsStackRef:
    Value: !Ref VPCSubnetsStack
  VPCFlowLogsStackRef:
    Value: !Ref VPCFlowLogsStack
  VPCRouteTablesStackRef:
    Value: !Ref VPCRouteTablesStack
  VPCNACLSStackRef:
    Value: !Ref VPCNACLSStack
  VPCSecurityGroupsStackRef:
    Value: !Ref VPCSecurityGroupsStack
