AWSTemplateFormatVersion: '2010-09-09'

Description:
    Template to deploy the Core VPC, Subnets, Internet Gateway, VPC Peering Connection and S3 Endpoints.


Resources:

   #Customer VPC
   VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 20.156.32.0/24        
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: Test-vpc-from-cfn-stack

   #DMZ Subnet 1 - Availability Zone 1
   DMZ1ASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2a      
      VpcId:
        Ref: VPC
      CidrBlock: 20.156.32.0/25        
      Tags:
      - Key: Name
        Value: DMZ-1A

   #DMZ Subnet 2 - Availability Zone 2
   DMZ1BSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2b
      VpcId:
        Ref: VPC
      CidrBlock: 20.156.32.128/25
      Tags:
      - Key: Name
        Value: DMZ-1B 